(function(){
'use strict';
var sb=null,session=null;
var DIST=['הכול או כלום','הכללת יתר','מסנן שלילי','פסילת החיובי','קריאת מחשבות','ניבוי העתיד','קטסטרופיזציה','הגדלה או הקטנה','חשיבה רגשית','צריך / חייב','תיוג','האשמה עצמית או אחרים'];
function q(s){return document.querySelector(s)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function client(){var c=window.ANGEL_SUPABASE;if(!c||!window.supabase)return null;return window.AngelSupabaseClient||(window.AngelSupabaseClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}))}
function toast(t){var x=document.createElement('div');x.textContent=t;x.style.cssText='position:fixed;z-index:1900;left:14px;right:14px;bottom:90px;max-width:440px;margin:auto;background:#1f2749;color:#fff;padding:12px;border-radius:14px;text-align:center;font-family:Assistant,system-ui';document.body.appendChild(x);setTimeout(function(){x.remove()},2800)}
function css(){if(q('#acbtcss'))return;var s=document.createElement('style');s.id='acbtcss';s.textContent='.acbtcard{background:linear-gradient(145deg,#fff8e9,#f5f1ff);border:1px solid #eadfbd;border-radius:20px;padding:16px;margin:12px 0}.acbtbtn{width:100%;min-height:48px;border-radius:14px;background:#1f2749;color:#fff;font-weight:800}.acbtov{position:fixed;inset:0;z-index:1850;background:#edf0fa;color:#1f2749;overflow:auto}.acbtwrap{max-width:560px;margin:auto;padding:20px 16px 80px}.acbttop{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.acbttop h1{font-family:Suez One,Assistant,serif;font-size:25px;margin:0}.acbtclose{min-height:42px;padding:0 14px;border-radius:12px;background:#fff;border:1px solid #dfe3ef}.acbtpanel{background:#fff;border:1px solid #dfe3ef;border-radius:20px;padding:16px;margin-bottom:12px}.acbtpanel label{display:block;font-weight:800;font-size:13px;margin:12px 0 5px}.acbtpanel textarea,.acbtpanel input{width:100%;border:1px solid #d8deeb;border-radius:13px;padding:11px;font:inherit;min-height:44px}.acbtpanel textarea{min-height:82px;resize:vertical}.acbtdist{display:flex;flex-wrap:wrap;gap:7px}.acbtdist label{margin:0;font-weight:700;font-size:12px;background:#f1f3f8;border-radius:99px;padding:8px 10px}.acbtdist input{width:auto;min-height:0;margin-left:5px}.acbtprimary{width:100%;min-height:50px;border:0;border-radius:14px;background:#ffc24d;color:#33270b;font-weight:900}.acbtentry{padding:12px 0;border-bottom:1px solid #edf0f5}.acbtentry:last-child{border-bottom:0}.acbtmeta{font-size:12px;color:#747d9a}.acbtpattern{display:inline-block;background:#f0edff;color:#5952a5;border-radius:99px;padding:4px 7px;font-size:11px;margin:3px}.acbtdisclaimer{background:#fff7df;border:1px solid #ecd79b;border-radius:14px;padding:11px;font-size:12px;line-height:1.55;margin-bottom:12px}';document.head.appendChild(s)}
function inject(){var save=q('[data-a4-save]');if(!save||q('[data-acbt-open]'))return;var sec=document.createElement('section');sec.className='acbtcard';sec.innerHTML='<b style="font-size:17px">המסלול שלי</b><p style="margin:6px 0 12px;color:#626b88;font-size:13px">מרחב CBT אישי לזיהוי מחשבות אוטומטיות, רגשות ועיוותי חשיבה שחוזרים אצלך.</p><button class="acbtbtn" data-acbt-open>פתיחת CBT אישי</button>';var card=save.closest('.a4card');if(card)card.insertAdjacentElement('afterend',sec)}
function form(){return '<section class="acbtpanel"><h2 style="margin:0 0 4px;font-size:19px">רישום מחשבה</h2><div class="acbtmeta">המטרה היא לעצור רגע ולבדוק את הפרשנות, לא לשכנע את עצמך שהכול בסדר.</div><label>1. מה קרה?</label><textarea id="acbt-situation" placeholder="תאר/י בקצרה את המצב"></textarea><label>2. מה הייתה המחשבה האוטומטית?</label><textarea id="acbt-thought" placeholder="מה עבר לך בראש באותו רגע?"></textarea><label>3. מה הרגשת?</label><input id="acbt-emotion" placeholder="לדוגמה: חרדה, בושה, כעס, עצב"><label>עוצמת הרגש לפני הבדיקה — 0 עד 100</label><input id="acbt-intensity" type="number" min="0" max="100" placeholder="70"><label>4. אילו עיוותי חשיבה אולי מופיעים כאן?</label><div class="acbtdist">'+DIST.map(function(d,i){return '<label><input type="checkbox" data-acbt-dist value="'+esc(d)+'">'+esc(d)+'</label>'}).join('')+'</div><label>5. אילו עובדות תומכות במחשבה?</label><textarea id="acbt-for"></textarea><label>6. אילו עובדות לא מתאימות למחשבה או מציעות הסבר אחר?</label><textarea id="acbt-against"></textarea><label>7. מה תהיה מחשבה מאוזנת יותר?</label><textarea id="acbt-balanced" placeholder="לא חיובית בכוח — פשוט מדויקת והוגנת יותר"></textarea><label>עוצמת הרגש עכשיו — 0 עד 100</label><input id="acbt-new" type="number" min="0" max="100"><button class="acbtprimary" data-acbt-save style="margin-top:14px">שמירת הרישום</button></section>'}
function overlay(){var d=document.createElement('div');d.id='acbtov';d.className='acbtov';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.innerHTML='<div class="acbtwrap"><div class="acbttop"><div><h1>CBT אישי — לזהות את הדפוס</h1><div class="acbtmeta">המסלול שלי</div></div><button class="acbtclose" data-acbt-close>חזרה לפרופיל</button></div><div class="acbtdisclaimer"><b>חשוב:</b> זהו כלי להכוונה עצמית ולתיעוד אישי. הוא אינו אבחון, טיפול פסיכולוגי או תחליף לאיש מקצוע. אם המחשבות או המצוקה מרגישות מסוכנות או בלתי נשלטות, יש להשתמש במסלול העזרה הדחופה באפליקציה או לפנות לעזרה מקצועית.</div><div id="acbt-summary"></div>'+form()+'<section class="acbtpanel"><h2 style="margin:0 0 8px;font-size:19px">הרישומים שלי</h2><div id="acbt-history">טוען…</div></section></div>';document.body.appendChild(d);loadHistory()}
function val(id){var e=q(id);return e?e.value.trim():''}
async function save(){if(!session)return toast('צריך להתחבר');var situation=val('#acbt-situation'),thought=val('#acbt-thought');if(!situation||!thought)return toast('צריך למלא לפחות מצב ומחשבה אוטומטית');var ds=[].slice.call(document.querySelectorAll('[data-acbt-dist]:checked')).map(function(x){return x.value});var payload={user_id:session.user.id,situation:situation,automatic_thought:thought,emotion:val('#acbt-emotion')||null,emotion_intensity:val('#acbt-intensity')===''?null:Number(val('#acbt-intensity')),distortions:ds,evidence_for:val('#acbt-for')||null,evidence_against:val('#acbt-against')||null,balanced_thought:val('#acbt-balanced')||null,new_intensity:val('#acbt-new')===''?null:Number(val('#acbt-new'))};var r=await sb.from('cbt_checkins').insert(payload);if(r.error)return toast('הרישום לא נשמר');toast('הרישום נשמר באופן פרטי ✓');q('#acbt-situation').value='';q('#acbt-thought').value='';q('#acbt-emotion').value='';q('#acbt-intensity').value='';q('#acbt-for').value='';q('#acbt-against').value='';q('#acbt-balanced').value='';q('#acbt-new').value='';document.querySelectorAll('[data-acbt-dist]').forEach(function(x){x.checked=false});loadHistory()}
function summary(rows){var counts={};rows.forEach(function(r){(r.distortions||[]).forEach(function(d){counts[d]=(counts[d]||0)+1})});var top=Object.keys(counts).sort(function(a,b){return counts[b]-counts[a]}).slice(0,3);var box=q('#acbt-summary');if(!box)return;if(!rows.length){box.innerHTML='<section class="acbtpanel"><b>עוד אין דפוס מזוהה.</b><div class="acbtmeta">אחרי כמה רישומים Angel יוכל להראות אילו עיוותי חשיבה מסומנים אצלך שוב ושוב.</div></section>';return}box.innerHTML='<section class="acbtpanel"><b>הדפוסים שחוזרים ברישומים שלך</b><div style="margin-top:8px">'+(top.length?top.map(function(d){return '<span class="acbtpattern">'+esc(d)+' · '+counts[d]+'</span>'}).join(''):'<span class="acbtmeta">עדיין לא סימנת עיוותי חשיבה.</span>')+'</div><div class="acbtmeta" style="margin-top:8px">זהו סיכום של הסימונים שלך בלבד, לא אבחון אוטומטי.</div></section>'}
async function loadHistory(){if(!session)return;var r=await sb.from('cbt_checkins').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(30);if(r.error){var h=q('#acbt-history');if(h)h.textContent='לא ניתן לטעון כרגע';return}var rows=r.data||[];summary(rows);var h=q('#acbt-history');if(!h)return;h.innerHTML=rows.length?rows.map(function(x){return '<div class="acbtentry"><div class="acbtmeta">'+new Date(x.created_at).toLocaleString('he-IL')+'</div><b>'+esc(x.situation)+'</b><div style="margin-top:4px">מחשבה: '+esc(x.automatic_thought)+'</div>'+(x.balanced_thought?'<div style="margin-top:4px;color:#376c5b">מחשבה מאוזנת: '+esc(x.balanced_thought)+'</div>':'')+'<div style="margin-top:5px">'+(x.distortions||[]).map(function(d){return '<span class="acbtpattern">'+esc(d)+'</span>'}).join('')+'</div></div>'}).join(''):'<div class="acbtmeta">עוד אין רישומים.</div>'}
function bind(){document.addEventListener('click',function(ev){var t=ev.target.closest&&ev.target.closest('[data-acbt-open],[data-acbt-close],[data-acbt-save]');if(!t)return;if(t.hasAttribute('data-acbt-open'))overlay();else if(t.hasAttribute('data-acbt-close')){var o=q('#acbtov');if(o)o.remove()}else if(t.hasAttribute('data-acbt-save'))save()},true);new MutationObserver(inject).observe(document.body,{childList:true,subtree:true})}
async function boot(){css();bind();sb=client();if(!sb)return setTimeout(boot,120);var r=await sb.auth.getSession();session=r.data.session;sb.auth.onAuthStateChange(function(_e,s){session=s});inject()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();