(function(){
'use strict';
var sb=null,session=null,ch=null,items=[],unread=0;
function q(s){return document.querySelector(s)}
function client(){var c=window.ANGEL_SUPABASE;if(!c||!window.supabase)return null;return window.AngelSupabaseClient||(window.AngelSupabaseClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}))}
function css(){if(q('#anotifcss'))return;var s=document.createElement('style');s.id='anotifcss';s.textContent='.anbtn{position:fixed;top:calc(14px + env(safe-area-inset-top));left:14px;z-index:2250;width:46px;height:46px;border:1px solid #dde2f2;border-radius:50%;background:#fff;box-shadow:0 8px 28px rgba(31,39,73,.16);font-size:21px}.anbadge{position:absolute;top:-3px;right:-3px;min-width:19px;height:19px;border-radius:99px;background:#ee6e8c;color:#fff;font:700 11px/19px Assistant;text-align:center;padding:0 4px}.anpanel{position:fixed;z-index:2249;top:calc(67px + env(safe-area-inset-top));left:12px;width:min(360px,calc(100vw - 24px));max-height:62vh;overflow:auto;background:#fff;border:1px solid #dde2f2;border-radius:20px;box-shadow:0 14px 40px rgba(31,39,73,.22);padding:12px;color:#1f2749}.anhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.anitem{padding:11px;border-radius:14px;background:#f6f7fb;margin-top:7px}.anitem b{display:block}.anitem span{font-size:12px;color:#68718f}.antoast{position:fixed;z-index:2300;left:14px;right:14px;top:calc(72px + env(safe-area-inset-top));max-width:440px;margin:auto;background:#1f2749;color:#fff;border-radius:15px;padding:12px 14px;box-shadow:0 10px 30px rgba(0,0,0,.2);font-family:Assistant,system-ui}.anhidden{display:none!important}';document.head.appendChild(s)}
function ensureUI(){if(q('#anbtn'))return;var b=document.createElement('button');b.id='anbtn';b.className='anbtn';b.type='button';b.setAttribute('aria-label','התראות');b.innerHTML='🔔<span id="anbadge" class="anbadge anhidden">0</span>';document.body.appendChild(b);var p=document.createElement('section');p.id='anpanel';p.className='anpanel anhidden';p.setAttribute('aria-label','התראות');p.innerHTML='<div class="anhead"><b>התראות</b><button id="anclear" type="button">סמן כנקרא</button></div><div id="anlist"><div class="anitem">אין התראות חדשות.</div></div>';document.body.appendChild(p);b.onclick=function(){p.classList.toggle('anhidden');if(!p.classList.contains('anhidden')){unread=0;draw()}};q('#anclear').onclick=function(){unread=0;draw()}}
function draw(){ensureUI();var badge=q('#anbadge');badge.textContent=unread>99?'99+':String(unread);badge.classList.toggle('anhidden',unread<1);var l=q('#anlist');l.innerHTML=items.length?items.slice(0,25).map(function(x){return '<div class="anitem"><b>'+esc(x.title)+'</b><div>'+esc(x.body)+'</div><span>'+new Date(x.at).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'})+'</span></div>'}).join(''):'<div class="anitem">אין התראות חדשות.</div>'}
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function push(title,body){items.unshift({title:title,body:body,at:Date.now()});unread++;draw();var t=document.createElement('div');t.className='antoast';t.innerHTML='<b>'+esc(title)+'</b><div>'+esc(body)+'</div>';document.body.appendChild(t);setTimeout(function(){t.remove()},4200)}
async function nameOf(id){if(!id)return 'מישהו';var r=await sb.from('profiles').select('display_name,is_anonymous').eq('id',id).maybeSingle();return r.data?(r.data.is_anonymous?'חבר/ת קהילה':r.data.display_name||'חבר/ת קהילה'):'חבר/ת קהילה'}
function subscribe(){if(!session||!sb)return;if(ch){try{sb.removeChannel(ch)}catch(e){}}ch=sb.channel('angel-notifications-'+session.user.id)
.on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async function(p){var n=p.new;if(!n||n.sender_id===session.user.id)return;push('הודעה חדשה',await nameOf(n.sender_id))})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_messages'},async function(p){var n=p.new;if(!n||n.sender_id===session.user.id)return;var g=await sb.from('groups').select('name').eq('id',n.group_id).maybeSingle();push('הודעה בקבוצה',g.data&&g.data.name?g.data.name:'קבוצה')})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions',filter:'callee_id=eq.'+session.user.id},async function(p){var n=p.new;if(!n)return;push(n.media_type==='video'?'שיחת וידאו נכנסת':'שיחה נכנסת',await nameOf(n.caller_id))})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_video_rooms'},async function(p){var n=p.new;if(!n||n.host_id===session.user.id)return;var m=await sb.from('group_members').select('group_id').eq('group_id',n.group_id).eq('user_id',session.user.id).maybeSingle();if(!m.data)return;var g=await sb.from('groups').select('name').eq('id',n.group_id).maybeSingle();push('שיחת וידאו קבוצתית התחילה',g.data&&g.data.name?g.data.name:'אחת הקבוצות שלך')})
.subscribe()}
async function boot(){css();ensureUI();sb=client();if(!sb)return setTimeout(boot,120);var r=await sb.auth.getSession();session=r.data.session;if(session)subscribe();sb.auth.onAuthStateChange(function(_e,s){session=s;if(s)subscribe();else if(ch){sb.removeChannel(ch);ch=null}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();