(function(){
'use strict';
var sb=null,session=null,stories=[],profiles={},refreshTimer=null;
function q(s){return document.querySelector(s)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function toast(t){var x=document.createElement('div');x.textContent=t;x.style.cssText='position:fixed;z-index:1200;left:14px;right:14px;bottom:92px;max-width:440px;margin:auto;background:#1f2749;color:white;padding:12px;border-radius:14px;text-align:center;font-family:Assistant,system-ui';document.body.appendChild(x);setTimeout(function(){x.remove()},2600)}
function css(){if(q('#angelStoriesCss'))return;var s=document.createElement('style');s.id='angelStoriesCss';s.textContent=`
#angelStories{max-width:470px;margin:0 auto;padding:8px 10px 2px;direction:rtl}#angelStories *{box-sizing:border-box}.st-head{display:flex;align-items:center;justify-content:space-between;padding:0 4px 6px}.st-title{font-weight:800;color:#1f2749}.st-strip{display:flex;gap:11px;overflow-x:auto;padding:4px 2px 10px;scrollbar-width:none}.st-strip::-webkit-scrollbar{display:none}.st-item{flex:0 0 auto;width:70px;text-align:center;background:none;border:0;padding:0}.st-ring{width:62px;height:62px;border-radius:50%;padding:3px;background:linear-gradient(135deg,#ffc24d,#ee6e8c,#8e86e0);margin:auto;position:relative}.st-inner{width:100%;height:100%;border-radius:50%;background:white;border:2px solid white;display:grid;place-items:center;overflow:hidden;font-weight:800;color:#28315e}.st-inner img,.st-inner video{width:100%;height:100%;object-fit:cover}.st-name{font-size:11px;color:#4f5878;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.st-add .st-ring{background:#eef0f7}.st-plus{position:absolute;bottom:-1px;left:-1px;width:22px;height:22px;border-radius:50%;background:#28315e;color:white;border:2px solid white;display:grid;place-items:center;font-size:15px}.st-view{position:fixed;inset:0;z-index:1100;background:#111;display:flex;align-items:center;justify-content:center}.st-media{max-width:100%;max-height:100%;width:100%;height:100%;object-fit:contain}.st-top{position:absolute;top:0;left:0;right:0;padding:calc(16px + env(safe-area-inset-top)) 16px 12px;background:linear-gradient(rgba(0,0,0,.55),transparent);display:flex;align-items:center;gap:9px;color:white;z-index:2}.st-av{width:38px;height:38px;border-radius:50%;overflow:hidden;background:#fff;color:#28315e;display:grid;place-items:center;font-weight:800}.st-av img{width:100%;height:100%;object-fit:cover}.st-close{margin-right:auto;color:#fff;font-size:28px;background:none;border:0}.st-caption{position:absolute;bottom:calc(28px + env(safe-area-inset-bottom));left:18px;right:18px;color:white;text-align:center;font-weight:700;text-shadow:0 1px 4px #000;z-index:2}.st-nav{position:absolute;inset:0;display:flex;z-index:1}.st-nav button{flex:1;border:0;background:transparent}.st-upload{position:fixed;inset:0;z-index:1150;background:rgba(17,20,35,.72);display:flex;align-items:flex-end;justify-content:center}.st-sheet{width:100%;max-width:470px;background:white;border-radius:26px 26px 0 0;padding:20px 18px calc(24px + env(safe-area-inset-bottom));color:#1f2749}.st-sheet input,.st-sheet textarea{width:100%;border:1px solid #dce1ec;border-radius:14px;padding:11px;font:inherit;margin-top:8px}.st-sheet textarea{min-height:70px}.st-actions{display:flex;gap:8px;margin-top:12px}.st-btn{flex:1;height:46px;border:0;border-radius:14px;font-weight:800}.st-btn.dark{background:#28315e;color:#fff}.st-btn.soft{background:#eef0f7;color:#28315e}
`;document.head.appendChild(s)}
function shared(){var c=window.ANGEL_SUPABASE;if(!c||!window.supabase)return null;return window.AngelSupabaseClient||(window.AngelSupabaseClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}))}
function fixLegacyChat(){document.addEventListener('click',function(ev){var b=ev.target.closest&&ev.target.closest('.btn-icon[data-act="call"]');if(!b||!b.getAttribute('aria-label')||b.getAttribute('aria-label').indexOf('הודעה')!==0)return;ev.preventDefault();ev.stopImmediatePropagation();var chats=document.querySelector('nav [data-id="chats"]');if(chats)chats.click();else toast('פתחו את אזור השיחות')},true)}
function initials(p){return (p&&p.display_name||'?').trim().charAt(0)||'?'}
function profileAvatar(p){return p&&p.avatar_url?'<img src="'+esc(p.avatar_url)+'" alt="">':esc(initials(p))}
function ensureStrip(){if(!session){var old=q('#angelStories');if(old)old.remove();return}var main=q('#a3mount')||q('main.wrap')||q('#socialMount')||q('#v2mount');if(!main)return;if(!q('#angelStories')){var d=document.createElement('section');d.id='angelStories';main.parentNode.insertBefore(d,main)}renderStrip()}
function grouped(){var map={},out=[];stories.forEach(function(st){if(!map[st.author_id]){map[st.author_id]=[];out.push({id:st.author_id,items:map[st.author_id]})}map[st.author_id].push(st)});return out}
function thumb(st){if(!st)return '';return st.media_type==='video'?'<video src="'+esc(st.media_url)+'" muted playsinline></video>':'<img src="'+esc(st.media_url)+'" alt="">'}
function renderStrip(){var el=q('#angelStories');if(!el||!session)return;var gs=grouped();var mine=profiles[session.user.id]||{display_name:'הסטורי שלי'};var html='<div class="st-head"><div class="st-title">סטוריז</div><div style="font-size:11px;color:#7a839f">נעלמים אחרי 24 שעות</div></div><div class="st-strip">';html+='<button class="st-item st-add" data-st-add><div class="st-ring"><div class="st-inner">'+profileAvatar(mine)+'</div><span class="st-plus">+</span></div><div class="st-name">הסטורי שלך</div></button>';gs.forEach(function(g){var p=profiles[g.id]||{},st=g.items[0];html+='<button class="st-item" data-st-open="'+g.id+'"><div class="st-ring"><div class="st-inner">'+thumb(st)+'</div></div><div class="st-name">'+esc(p.is_anonymous?'חבר/ת קהילה':p.display_name||'חבר/ת קהילה')+'</div></button>'});html+='</div>';el.innerHTML=html}
async function load(){if(!session)return;var r=await sb.from('stories').select('*').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false});stories=r.data||[];var ids=[session.user.id].concat(stories.map(function(x){return x.author_id}));ids=[...new Set(ids)];if(ids.length){var p=await sb.from('profiles').select('id,display_name,avatar_url,is_anonymous').in('id',ids);profiles={};(p.data||[]).forEach(function(x){profiles[x.id]=x})}ensureStrip()}
function uploadSheet(){var old=q('#stUpload');if(old)old.remove();var d=document.createElement('div');d.id='stUpload';d.className='st-upload';d.innerHTML='<div class="st-sheet"><h3 style="margin:0">סטורי חדש</h3><div style="font-size:13px;color:#737c99">תמונה או וידאו עד 25MB · יימחק מהפיד אחרי 24 שעות</div><input id="stFile" type="file" accept="image/*,video/*"><textarea id="stCaption" placeholder="כיתוב (אופציונלי)"></textarea><div class="st-actions"><button class="st-btn soft" data-st-cancel>ביטול</button><button class="st-btn dark" data-st-upload>העלאה</button></div></div>';document.body.appendChild(d)}
async function upload(){var f=q('#stFile')&&q('#stFile').files[0],cap=q('#stCaption')?q('#stCaption').value.trim():'';if(!f)return toast('בחרו תמונה או וידאו');if(f.size>25*1024*1024)return toast('הקובץ גדול מדי. עד 25MB');var type=f.type.indexOf('video/')===0?'video':'image';var ext=(f.name.split('.').pop()|| (type==='video'?'mp4':'jpg')).toLowerCase();var path=session.user.id+'/'+Date.now()+'.'+ext;var btn=q('[data-st-upload]');if(btn){btn.disabled=true;btn.textContent='מעלה…'}var u=await sb.storage.from('story-media').upload(path,f,{upsert:false,contentType:f.type});if(u.error){if(btn){btn.disabled=false;btn.textContent='העלאה'}return toast('העלאת הסטורי נכשלה')};var url=sb.storage.from('story-media').getPublicUrl(path).data.publicUrl;var r=await sb.from('stories').insert({author_id:session.user.id,media_url:url,media_type:type,caption:cap});if(r.error){toast('שמירת הסטורי נכשלה');return}var sh=q('#stUpload');if(sh)sh.remove();toast('הסטורי עלה ✓');await load()}
var viewAuthor=null,viewIndex=0;
function authorStories(id){return stories.filter(function(x){return x.author_id===id}).sort(function(a,b){return new Date(a.created_at)-new Date(b.created_at)})}
function openStory(id,index){viewAuthor=id;viewIndex=index||0;renderViewer()}
function renderViewer(){var arr=authorStories(viewAuthor);if(!arr.length)return closeViewer();if(viewIndex<0)viewIndex=0;if(viewIndex>=arr.length)return closeViewer();var st=arr[viewIndex],p=profiles[st.author_id]||{};var old=q('#stViewer');if(old)old.remove();var d=document.createElement('div');d.id='stViewer';d.className='st-view';var media=st.media_type==='video'?'<video class="st-media" src="'+esc(st.media_url)+'" autoplay playsinline controls></video>':'<img class="st-media" src="'+esc(st.media_url)+'" alt="">';d.innerHTML=media+'<div class="st-top"><div class="st-av">'+profileAvatar(p)+'</div><div><div style="font-weight:800">'+esc(p.is_anonymous?'חבר/ת קהילה':p.display_name||'חבר/ת קהילה')+'</div><div style="font-size:11px;opacity:.8">סטורי</div></div><button class="st-close" data-st-close>×</button></div>'+(st.caption?'<div class="st-caption">'+esc(st.caption)+'</div>':'')+'<div class="st-nav"><button data-st-prev aria-label="הקודם"></button><button data-st-next aria-label="הבא"></button></div>';document.body.appendChild(d)}
function closeViewer(){var x=q('#stViewer');if(x)x.remove();viewAuthor=null;viewIndex=0}
function bind(){document.addEventListener('click',function(ev){var t=ev.target.closest&&ev.target.closest('[data-st-add],[data-st-open],[data-st-cancel],[data-st-upload],[data-st-close],[data-st-prev],[data-st-next]');if(!t)return;if(t.hasAttribute('data-st-add'))uploadSheet();else if(t.hasAttribute('data-st-open'))openStory(t.getAttribute('data-st-open'),0);else if(t.hasAttribute('data-st-cancel')){var x=q('#stUpload');if(x)x.remove()}else if(t.hasAttribute('data-st-upload'))upload();else if(t.hasAttribute('data-st-close'))closeViewer();else if(t.hasAttribute('data-st-prev')){viewIndex--;renderViewer()}else if(t.hasAttribute('data-st-next')){viewIndex++;renderViewer()}},true);new MutationObserver(function(){ensureStrip()}).observe(document.body,{childList:true,subtree:true})}
async function boot(){css();fixLegacyChat();bind();sb=shared();if(!sb)return setTimeout(boot,120);var r=await sb.auth.getSession();session=r.data.session;sb.auth.onAuthStateChange(function(_e,s){session=s;if(session)load();else ensureStrip()});if(session)await load();clearInterval(refreshTimer);refreshTimer=setInterval(load,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();