(function(){
var sb=null,session=null;
var SITE='https://roeekim-alt.github.io/Angel/';
function toast(m){var x=document.createElement('div');x.textContent=m;x.style='position:fixed;z-index:500;left:16px;right:16px;bottom:90px;max-width:408px;margin:auto;background:#1F2749;color:white;padding:12px;border-radius:14px;text-align:center;font-family:Assistant';document.body.appendChild(x);setTimeout(function(){x.remove()},3200)}
function translateError(err){var s=(err&&err.message||String(err||'')).toLowerCase();if(s.indexOf('email not confirmed')>-1)return 'המייל עדיין לא אומת.';if(s.indexOf('rate limit')>-1||s.indexOf('security purposes')>-1)return 'נשלחו יותר מדי בקשות בזמן קצר. המתן מעט ונסה שוב.';if(s.indexOf('invalid login credentials')>-1)return 'האימייל או הסיסמה אינם נכונים.';if(s.indexOf('already_registered')>-1)return 'החשבון כבר קיים. לחץ על התחברות.';if(s.indexOf('weak_password')>-1)return 'ליצירת חשבון חדש הסיסמה חייבת להכיל לפחות 8 תווים.';return err&&err.message?err.message:'אירעה שגיאה. נסה שוב.'}
function modal(){var old=document.getElementById('angelAuth');if(old)old.remove();var d=document.createElement('div');d.id='angelAuth';d.style='position:fixed;inset:0;z-index:480;background:#EDF0FA;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Assistant;color:#1F2749';d.innerHTML='<div style="width:100%;max-width:410px;background:white;border-radius:24px;padding:20px"><h2>ברוכים הבאים לאנג׳ל</h2><p>כדי ליצור פרופיל צריך חשבון.</p><input id="sbEmail" type="email" placeholder="אימייל" autocomplete="email" style="box-sizing:border-box;width:100%;padding:12px;margin-bottom:8px"><input id="sbPass" type="password" placeholder="סיסמה" autocomplete="current-password" style="box-sizing:border-box;width:100%;padding:12px;margin-bottom:6px"><div style="font-size:12px;color:#6f7897;margin-bottom:10px">להתחברות: 6 תווים לפחות · להרשמה חדשה: 8 תווים לפחות</div><div style="display:flex;gap:8px"><button id="sbLogin" style="flex:1;padding:12px;background:#1F2749;color:white;border:0;border-radius:12px">התחברות</button><button id="sbSignup" style="flex:1;padding:12px;background:#FFC24D;border:0;border-radius:12px">יצירת חשבון</button></div><button id="sbResend" style="width:100%;margin-top:8px;padding:11px;border:1px solid #D7DCEF;background:#fff;color:#1F2749;border-radius:12px;font-weight:700">שלח מייל אימות מחדש</button><button id="sbGuest" style="width:100%;margin-top:8px;padding:10px;border:0;border-radius:12px">המשך צפייה</button><p id="sbMsg" style="line-height:1.5"></p></div>';document.body.appendChild(d);document.getElementById('sbGuest').onclick=function(){d.remove()};document.getElementById('sbLogin').onclick=function(){login()};document.getElementById('sbSignup').onclick=function(){signup()};document.getElementById('sbResend').onclick=resend}
window.AngelAuthOpen=modal;
function credentials(min){var email=document.getElementById('sbEmail').value.trim(),password=document.getElementById('sbPass').value,msg=document.getElementById('sbMsg');if(!email||password.length<min){msg.textContent='הזן אימייל וסיסמה של לפחות '+min+' תווים';return null}return {email:email,password:password,msg:msg}}
async function login(){var c=credentials(6);if(!c)return;c.msg.textContent='מתחבר…';var r=await sb.auth.signInWithPassword({email:c.email,password:c.password});if(r.error){c.msg.textContent=translateError(r.error);return}session=r.data.session;document.getElementById('angelAuth')?.remove();toast('התחברת בהצלחה')}
async function signup(){var c=credentials(8);if(!c)return;var btn=document.getElementById('sbSignup');btn.disabled=true;c.msg.textContent='יוצר חשבון…';try{var res=await fetch(window.ANGEL_SUPABASE.url+'/functions/v1/angel-signup',{method:'POST',headers:{'Content-Type':'application/json','apikey':window.ANGEL_SUPABASE.key},body:JSON.stringify({email:c.email,password:c.password})});var out=await res.json();if(!res.ok&&out.error!=='already_registered')throw new Error(out.error||out.message||'signup_failed');if(out.error==='already_registered'){c.msg.textContent='החשבון כבר קיים. נסה להתחבר.';return}var r=await sb.auth.signInWithPassword({email:c.email,password:c.password});if(r.error)throw r.error;session=r.data.session;document.getElementById('angelAuth')?.remove();toast('החשבון נוצר והתחברת ✓')}catch(err){c.msg.textContent=translateError(err)}finally{btn.disabled=false}}
async function resend(){var email=document.getElementById('sbEmail').value.trim(),msg=document.getElementById('sbMsg'),btn=document.getElementById('sbResend');if(!email){msg.textContent='הזן קודם את כתובת האימייל שלך.';return}btn.disabled=true;btn.textContent='שולח…';var r=await sb.auth.resend({type:'signup',email:email,options:{emailRedirectTo:SITE}});if(r.error){msg.textContent=translateError(r.error);btn.disabled=false;btn.textContent='שלח מייל אימות מחדש';return}msg.textContent='מייל אימות חדש נשלח.';var sec=60;btn.textContent='אפשר לשלוח שוב בעוד '+sec+' שניות';var tm=setInterval(function(){sec--;if(sec<=0){clearInterval(tm);btn.disabled=false;btn.textContent='שלח מייל אימות מחדש'}else btn.textContent='אפשר לשלוח שוב בעוד '+sec+' שניות'},1000)}
async function boot(){var c=window.ANGEL_SUPABASE;if(!c)return;sb=window.AngelSupabaseClient||(window.AngelSupabaseClient=window.supabase.createClient(c.url,c.key));var r=await sb.auth.getSession();session=r.data.session;if(!session)setTimeout(modal,250);sb.auth.onAuthStateChange(function(_e,s){session=s})}
function start(){if(window.supabase)boot();else{var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;document.head.appendChild(s)}}
start();
})();