(function(){
var sb=null,session=null;
function toast(m){var x=document.createElement('div');x.textContent=m;x.style='position:fixed;z-index:200;left:16px;right:16px;bottom:90px;max-width:408px;margin:auto;background:#1F2749;color:white;padding:12px;border-radius:14px;text-align:center;font-family:Assistant';document.body.appendChild(x);setTimeout(function(){x.remove()},3000)}
function translateError(err){var s=(err&&err.message||'').toLowerCase();if(s.indexOf('email not confirmed')>-1)return 'המייל עדיין לא אומת. פתח את הודעת האימות שקיבלת או שלח מייל אימות מחדש.';if(s.indexOf('rate limit')>-1||s.indexOf('security purposes')>-1)return 'נשלחו יותר מדי בקשות בזמן קצר. המתן מעט ונסה שוב.';if(s.indexOf('invalid login credentials')>-1)return 'האימייל או הסיסמה אינם נכונים.';return err&&err.message?err.message:'אירעה שגיאה. נסה שוב.'}
function modal(){var old=document.getElementById('angelAuth');if(old)old.remove();var d=document.createElement('div');d.id='angelAuth';d.style='position:fixed;inset:0;z-index:180;background:#EDF0FA;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Assistant;color:#1F2749';d.innerHTML='<div style="width:100%;max-width:410px;background:white;border-radius:24px;padding:20px"><h2>ברוכים הבאים לאנג׳ל</h2><p>כדי ליצור פרופיל צריך חשבון.</p><input id="sbEmail" type="email" placeholder="אימייל" style="width:100%;padding:12px;margin-bottom:8px"><input id="sbPass" type="password" placeholder="סיסמה - לפחות 6 תווים" style="width:100%;padding:12px;margin-bottom:10px"><div style="display:flex;gap:8px"><button id="sbLogin" style="flex:1;padding:12px;background:#1F2749;color:white;border:0;border-radius:12px">התחברות</button><button id="sbSignup" style="flex:1;padding:12px;background:#FFC24D;border:0;border-radius:12px">יצירת חשבון</button></div><button id="sbResend" style="width:100%;margin-top:8px;padding:11px;border:1px solid #D7DCEF;background:#fff;color:#1F2749;border-radius:12px;font-weight:700">שלח מייל אימות מחדש</button><button id="sbGuest" style="width:100%;margin-top:8px;padding:10px;border:0;border-radius:12px">המשך צפייה</button><p id="sbMsg" style="line-height:1.5"></p></div>';document.body.appendChild(d);document.getElementById('sbGuest').onclick=function(){d.remove()};document.getElementById('sbLogin').onclick=function(){go(false)};document.getElementById('sbSignup').onclick=function(){go(true)};document.getElementById('sbResend').onclick=resend}
async function go(signup){var email=document.getElementById('sbEmail').value.trim(),password=document.getElementById('sbPass').value,msg=document.getElementById('sbMsg');if(!email||password.length<6){msg.textContent='הזן אימייל וסיסמה תקינה';return}msg.textContent=signup?'יוצר חשבון…':'מתחבר…';var r=signup?await sb.auth.signUp({email:email,password:password}):await sb.auth.signInWithPassword({email:email,password:password});if(r.error){msg.textContent=translateError(r.error);return}if(signup&&!r.data.session){msg.textContent='החשבון נוצר. נשלח אליך מייל אימות — לאחר האימות לחץ על התחברות.';return}session=r.data.session;document.getElementById('angelAuth')?.remove();toast('התחברת בהצלחה')}
async function resend(){var email=document.getElementById('sbEmail').value.trim(),msg=document.getElementById('sbMsg'),btn=document.getElementById('sbResend');if(!email){msg.textContent='הזן קודם את כתובת האימייל שלך.';return}btn.disabled=true;btn.textContent='שולח…';msg.textContent='';var r=await sb.auth.resend({type:'signup',email:email,options:{emailRedirectTo:'https://roeekim-alt.github.io/Angel/'}});if(r.error){msg.textContent=translateError(r.error);btn.disabled=false;btn.textContent='שלח מייל אימות מחדש';return}msg.textContent='מייל אימות חדש נשלח. פתח את המייל האחרון שקיבלת ולחץ על קישור האימות.';var sec=60;btn.textContent='אפשר לשלוח שוב בעוד '+sec+' שניות';var timer=setInterval(function(){sec--;if(sec<=0){clearInterval(timer);btn.disabled=false;btn.textContent='שלח מייל אימות מחדש'}else btn.textContent='אפשר לשלוח שוב בעוד '+sec+' שניות'},1000)}
async function save(){if(!session){modal();return}var n=document.getElementById('profileName'),b=document.getElementById('profileBio'),t=document.getElementById('profileTopics'),a=document.getElementById('profileAnon');var data={id:session.user.id,display_name:n&&n.value.trim()||session.user.email.split('@')[0],bio:b&&b.value.trim()||'',topics:t&&t.value?t.value.split(',').map(function(x){return x.trim()}).filter(Boolean):[],is_anonymous:!!(a&&a.checked),updated_at:new Date().toISOString()};var r=await sb.from('profiles').upsert(data,{onConflict:'id'});if(r.error)toast('שמירה נכשלה: '+r.error.message);else toast('הפרופיל נשמר בענן ✓')}
document.addEventListener('click',function(e){var x=e.target.closest&&e.target.closest('[data-social-act="save-profile"]');if(!x)return;e.preventDefault();e.stopImmediatePropagation();save()},true);
function boot(){var c=window.ANGEL_SUPABASE;sb=window.supabase.createClient(c.url,c.key);sb.auth.getSession().then(function(r){session=r.data.session;if(!session)setTimeout(modal,300)});sb.auth.onAuthStateChange(function(_e,s){session=s})}
if(window.supabase)boot();else{var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;document.head.appendChild(s)}
})();