(function(){
var sb=null,session=null;
function toast(m){var x=document.createElement('div');x.textContent=m;x.style='position:fixed;z-index:200;left:16px;right:16px;bottom:90px;max-width:408px;margin:auto;background:#1F2749;color:white;padding:12px;border-radius:14px;text-align:center;font-family:Assistant';document.body.appendChild(x);setTimeout(function(){x.remove()},3000)}
function modal(){var old=document.getElementById('angelAuth');if(old)old.remove();var d=document.createElement('div');d.id='angelAuth';d.style='position:fixed;inset:0;z-index:180;background:#EDF0FA;display:flex;align-items:center;justify-content:center;padding:20px;font-family:Assistant;color:#1F2749';d.innerHTML='<div style="width:100%;max-width:410px;background:white;border-radius:24px;padding:20px"><h2>ברוכים הבאים לאנג׳ל</h2><p>כדי ליצור פרופיל צריך חשבון.</p><input id="sbEmail" type="email" placeholder="אימייל" style="width:100%;padding:12px;margin-bottom:8px"><input id="sbPass" type="password" placeholder="סיסמה - לפחות 6 תווים" style="width:100%;padding:12px;margin-bottom:10px"><div style="display:flex;gap:8px"><button id="sbLogin" style="flex:1;padding:12px;background:#1F2749;color:white;border:0;border-radius:12px">התחברות</button><button id="sbSignup" style="flex:1;padding:12px;background:#FFC24D;border:0;border-radius:12px">יצירת חשבון</button></div><button id="sbGuest" style="width:100%;margin-top:8px;padding:10px;border:0;border-radius:12px">המשך צפייה</button><p id="sbMsg"></p></div>';document.body.appendChild(d);document.getElementById('sbGuest').onclick=function(){d.remove()};document.getElementById('sbLogin').onclick=function(){go(false)};document.getElementById('sbSignup').onclick=function(){go(true)}}
async function go(signup){var email=document.getElementById('sbEmail').value.trim(),password=document.getElementById('sbPass').value,msg=document.getElementById('sbMsg');if(!email||password.length<6){msg.textContent='הזן אימייל וסיסמה תקינה';return}var r=signup?await sb.auth.signUp({email:email,password:password}):await sb.auth.signInWithPassword({email:email,password:password});if(r.error){msg.textContent=r.error.message;return}if(signup&&!r.data.session){msg.textContent='נשלח מייל אימות. לאחר האימות התחבר.';return}session=r.data.session;document.getElementById('angelAuth')?.remove();toast('התחברת בהצלחה')}
async function save(){if(!session){modal();return}var n=document.getElementById('profileName'),b=document.getElementById('profileBio'),t=document.getElementById('profileTopics'),a=document.getElementById('profileAnon');var data={id:session.user.id,display_name:n&&n.value.trim()||session.user.email.split('@')[0],bio:b&&b.value.trim()||'',topics:t&&t.value?t.value.split(',').map(function(x){return x.trim()}).filter(Boolean):[],is_anonymous:!!(a&&a.checked),updated_at:new Date().toISOString()};var r=await sb.from('profiles').upsert(data,{onConflict:'id'});if(r.error)toast('שמירה נכשלה: '+r.error.message);else toast('הפרופיל נשמר בענן ✓')}
document.addEventListener('click',function(e){var x=e.target.closest&&e.target.closest('[data-social-act="save-profile"]');if(!x)return;e.preventDefault();e.stopImmediatePropagation();save()},true);
function boot(){var c=window.ANGEL_SUPABASE;sb=window.supabase.createClient(c.url,c.key);sb.auth.getSession().then(function(r){session=r.data.session;if(!session)setTimeout(modal,300)});sb.auth.onAuthStateChange(function(_e,s){session=s})}
if(window.supabase)boot();else{var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;document.head.appendChild(s)}
})();