(function(){
'use strict';
var sb=null,session=null,isAdmin=false,currentUid=null;
function q(s){return document.querySelector(s)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function toast(t){var x=document.createElement('div');x.className='twtoast';x.textContent=t;document.body.appendChild(x);setTimeout(function(){x.remove()},3000)}
function css(){if(q('#twCss'))return;var s=document.createElement('style');s.id='twCss';s.textContent=`
#twNavBtn{color:#98a1be}.twtop{padding:8px 0 14px}.twtop h1{margin:0;font-size:25px}.twcard{background:#fff;border:1px solid #e2e6f0;border-radius:21px;padding:15px;margin-bottom:11px}.twperson{display:flex;gap:12px;align-items:center}.twavatar{width:64px;height:64px;border-radius:20px;background:#edf0f7;display:grid;place-items:center;overflow:hidden;font-weight:800;font-size:24px;flex:none}.twavatar img{width:100%;height:100%;object-fit:cover}.twgrow{flex:1;min-width:0}.twname{font-weight:850;font-size:17px}.twverified{display:inline-block;background:#e7f7ef;color:#197052;border-radius:99px;padding:3px 8px;font-size:11px;margin-right:5px}.twmeta{color:#727b97;font-size:13px;margin-top:4px;line-height:1.5}.twactions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.twbtn{border:0;border-radius:13px;min-height:42px;padding:0 13px;font-weight:800;background:#f0f2f8;color:#1f2749}.twbtn.dark{background:#1f2749;color:#fff}.twbtn.gold{background:#ffc24d;color:#33270b}.twform label{display:block;font-weight:800;font-size:13px;margin:11px 0 5px}.twform input,.twform textarea{width:100%;box-sizing:border-box;border:1px solid #dce1ec;border-radius:13px;padding:10px 12px;font:inherit;background:#fff}.twform textarea{min-height:90px}.twwallpost{background:#fff;border:1px solid #e2e6f0;border-radius:18px;padding:14px;margin-bottom:10px}.twwallpost img{width:100%;max-height:420px;object-fit:cover;border-radius:14px;margin-top:10px}.twhero{text-align:center}.twhero .twavatar{width:100px;height:100px;border-radius:30px;margin:0 auto 10px}.twempty{text-align:center;color:#7a839f;padding:24px}.twtoast{position:fixed;z-index:1800;left:14px;right:14px;bottom:92px;max-width:440px;margin:auto;background:#1f2749;color:#fff;padding:12px;border-radius:14px;text-align:center}.twadmin{border:2px solid #ffc24d}.twstatus{border-radius:10px;padding:9px 11px;background:#f5f6fa;font-size:13px;margin-top:8px}
`;document.head.appendChild(s)}
function shared(){var c=window.ANGEL_SUPABASE;if(!c||!window.supabase)return null;return window.AngelSupabaseClient||(window.AngelSupabaseClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}))}
function nav(){var n=q('nav');if(!n)return;if(!q('#twNavBtn')){var b=document.createElement('button');b.id='twNavBtn';b.innerHTML='<span style="font-size:20px">⚕️</span><span>מטפלים</span>';var me=n.querySelector('[data-id="me"]');n.insertBefore(b,me||null)}}
function mount(html){var old=q('#a4mount')||q('main.wrap')||q('#socialMount')||q('#v2mount');if(!old)return;old.outerHTML='<main id="a4mount" style="max-width:470px;margin:0 auto;padding:14px 14px calc(112px + env(safe-area-inset-bottom));color:#1f2749">'+html+'</main>'}
function av(p){var n=(p.display_name||'?').charAt(0);return '<div class="twavatar">'+(p.avatar_url?'<img src="'+esc(p.avatar_url)+'" alt="">':esc(n))+'</div>'}
async function adminCheck(){var r=await sb.rpc('is_app_admin');isAdmin=!!r.data}
async function therapists(){if(!session)return;var r=await sb.from('profiles').select('*').eq('role','therapist').eq('therapist_verified',true).order('display_name');var arr=r.data||[];var html='<div class="twtop"><h1>מטפלים</h1><div class="twmeta">אנשי מקצוע שעברו אימות ואישור של Angel</div></div>';
html+='<div class="twcard"><b>מחפשים מטפל/ת?</b><div class="twmeta">אפשר לקרוא על כל מטפל, להיכנס לפרופיל ולקיר שלו וליצור קשר ישירות.</div></div>';
html+=arr.length?arr.map(function(p){return '<div class="twcard twperson">'+av(p)+'<div class="twgrow"><div class="twname">'+esc(p.display_name)+' <span class="twverified">✓ מאומת/ת</span></div><div class="twmeta">'+esc(p.therapist_specialty||'')+(p.therapist_location?' · '+esc(p.therapist_location):'')+'</div><div class="twactions"><button class="twbtn dark" data-tw-profile="'+p.id+'">לפרופיל</button><button class="twbtn gold" data-tw-chat="'+p.id+'">צ׳אט</button></div></div></div>'}).join(''):'<div class="twcard twempty">עדיין אין מטפלים מאומתים במערכת.</div>';
if(isAdmin)html+=await adminPanel();mount(html)}
async function adminPanel(){var r=await sb.from('therapist_applications').select('*').eq('status','pending').order('created_at',{ascending:true});var a=r.data||[];return '<div class="twcard twadmin"><b>ניהול בקשות מטפלים</b><div class="twmeta">אזור מנהל — בקשות שממתינות לאישור.</div>'+(a.length?a.map(function(x){return '<div style="border-top:1px solid #eee;margin-top:12px;padding-top:12px"><b>'+esc(x.full_name)+'</b><div class="twmeta">'+esc(x.profession)+' · '+esc(x.specialty)+'<br>רישיון: '+esc(x.license_number)+' '+esc(x.license_authority||'')+'<br>'+esc(x.professional_bio||'')+'</div><div class="twactions"><button class="twbtn dark" data-tw-approve="'+x.id+'">אישור מטפל</button><button class="twbtn" data-tw-reject="'+x.id+'">דחייה</button></div></div>'}).join(''):'<div class="twempty">אין בקשות ממתינות.</div>')+'</div>'}
async function publicProfile(uid){currentUid=uid;var r=await sb.from('profiles').select('*').eq('id',uid).maybeSingle();if(!r.data)return toast('הפרופיל לא נמצא');var p=r.data,vr=p.role==='therapist'&&p.therapist_verified;var wp=await sb.from('wall_posts').select('*').eq('author_id',uid).order('created_at',{ascending:false}).limit(50);var posts=wp.data||[];var mine=session&&session.user.id===uid;var html='<button class="twbtn" data-tw-back>← חזרה</button><div class="twcard twhero" style="margin-top:10px">'+av(p)+'<div class="twname" style="font-size:22px">'+esc(p.display_name||'')+(vr?' <span class="twverified">✓ מטפל/ת מאומת/ת</span>':'')+'</div><div class="twmeta">'+esc(p.bio||'')+'</div>';
if(vr)html+='<div class="twmeta" style="margin-top:10px"><b>'+esc(p.therapist_specialty||'')+'</b><br>'+esc(p.therapist_location||'')+(p.accepting_clients?'<br>מקבל/ת פניות חדשות':'')+'</div>';
if(!mine)html+='<div class="twactions" style="justify-content:center"><button class="twbtn gold" data-tw-chat="'+uid+'">צ׳אט</button><button class="twbtn dark" data-vc-call="'+uid+'">📹 וידאו</button></div>';html+='</div>';
if(mine)html+='<div class="twcard twform"><b>פרסום לקיר שלי</b><label>סטטוס</label><textarea id="twBody" placeholder="מה תרצו לשתף?"></textarea><label>תמונה</label><input id="twImage" type="file" accept="image/*"><button class="twbtn dark" data-tw-publish style="margin-top:10px">פרסום בקיר</button></div>';
html+='<div class="twtop"><h1>הקיר</h1></div>'+(posts.length?posts.map(function(x){return '<article class="twwallpost"><div class="twmeta">'+new Date(x.created_at).toLocaleString('he-IL')+'</div>'+(x.body?'<div style="white-space:pre-wrap;line-height:1.6;margin-top:7px">'+esc(x.body)+'</div>':'')+(x.image_url?'<img src="'+esc(x.image_url)+'" alt="">':'')+(mine?'<div class="twactions"><button class="twbtn" data-tw-delete="'+x.id+'">מחיקה</button></div>':'')+'</article>'}).join(''):'<div class="twcard twempty">עוד אין פרסומים בקיר.</div>');mount(html)}
async function uploadWall(file){if(!file)return null;if(file.size>10*1024*1024)throw new Error('תמונה עד 10MB');var ext=(file.name.split('.').pop()||'jpg').toLowerCase();var path=session.user.id+'/'+Date.now()+'.'+ext;var r=await sb.storage.from('wall-media').upload(path,file,{upsert:false,contentType:file.type});if(r.error)throw r.error;return sb.storage.from('wall-media').getPublicUrl(path).data.publicUrl}
async function publishWall(){var body=(q('#twBody').value||'').trim(),file=q('#twImage').files[0];if(!body&&!file)return toast('כתבו משהו או בחרו תמונה');try{var url=await uploadWall(file);var r=await sb.from('wall_posts').insert({author_id:session.user.id,body:body,image_url:url});if(r.error)throw r.error;toast('פורסם בקיר ✓');publicProfile(session.user.id)}catch(e){toast('הפרסום נכשל: '+e.message)}}
async function deleteWall(id){var r=await sb.from('wall_posts').delete().eq('id',id).eq('author_id',session.user.id);if(r.error)return toast('המחיקה נכשלה');publicProfile(session.user.id)}
async function directChat(uid){var p=await sb.from('profiles').select('display_name').eq('id',uid).maybeSingle();var c=await sb.rpc('get_or_create_direct_conversation',{other_user:uid});if(c.error)return toast('לא ניתן לפתוח צ׳אט');var cid=c.data;async function draw(){var m=await sb.from('messages').select('*').eq('conversation_id',cid).order('created_at',{ascending:true}).limit(150);mount('<button class="twbtn" data-tw-profile="'+uid+'">← לפרופיל</button><div class="twtop"><h1>'+esc(p.data&&p.data.display_name||'צ׳אט')+'</h1></div><div class="twcard">'+((m.data||[]).map(function(x){return '<div style="max-width:82%;padding:10px 12px;border-radius:14px;margin:6px 0;'+(x.sender_id===session.user.id?'background:#1f2749;color:#fff':'background:#f0f2f8;margin-right:auto')+'">'+esc(x.body)+'</div>'}).join('')||'<div class="twempty">אפשר להתחיל את השיחה כאן.</div>')+'<div style="display:flex;gap:7px;margin-top:12px"><input id="twMsg" style="flex:1;border:1px solid #dce1ec;border-radius:13px;padding:10px" placeholder="הודעה…"><button class="twbtn dark" data-tw-send="'+cid+'" data-tw-to="'+uid+'">שלח</button></div></div>')}draw()}
async function sendMsg(cid,uid){var b=(q('#twMsg').value||'').trim();if(!b)return;var r=await sb.from('messages').insert({conversation_id:cid,sender_id:session.user.id,body:b});if(r.error)return toast('ההודעה לא נשלחה');directChat(uid)}
async function submitApplication(){var val=function(id){return (q(id)&&q(id).value||'').trim()};var full=val('#twFull'),prof=val('#twProf'),lic=val('#twLic');if(!full||!prof||!lic)return toast('שם מלא, מקצוע ומספר רישיון הם שדות חובה');var yrs=parseInt(val('#twYears'),10);var r=await sb.rpc('submit_therapist_application',{p_full_name:full,p_profession:prof,p_specialty:val('#twSpec'),p_license_number:lic,p_license_authority:val('#twAuth'),p_experience_years:isNaN(yrs)?null:yrs,p_location:val('#twLoc'),p_languages:val('#twLang').split(',').map(function(x){return x.trim()}).filter(Boolean),p_professional_bio:val('#twBio'),p_accepting_clients:true});if(r.error)return toast('שליחת הבקשה נכשלה: '+r.error.message);toast('הבקשה נשלחה לאישור מנהל Angel ✓');enhanceOwnProfile(true)}
async function applicationBox(){var r=await sb.from('therapist_applications').select('*').eq('user_id',session.user.id).maybeSingle();var a=r.data;if(a&&a.status==='pending')return '<div class="twcard"><b>בקשת מטפל בבדיקה</b><div class="twstatus">הבקשה התקבלה וממתינה לאישור מנהל Angel.</div></div>';if(a&&a.status==='approved')return '<div class="twcard"><b>פרופיל מטפל מאומת ✓</b><div class="twstatus">הפרופיל אושר ומופיע באזור המטפלים.</div></div>';var note=a&&a.status==='rejected'&&a.review_note?'<div class="twstatus">הבקשה הקודמת נדחתה: '+esc(a.review_note)+'</div>':'';return '<div class="twcard twform"><b>בקשה לפתיחת פרופיל מטפל</b><div class="twmeta">פרופיל מטפל מתפרסם רק אחרי בדיקת רישיון ואישור מנהל Angel.</div>'+note+'<label>שם מלא</label><input id="twFull"><label>מקצוע</label><input id="twProf" placeholder="פסיכולוג/ית, עו״ס, פסיכותרפיסט/ית…"><label>תחום התמחות</label><input id="twSpec"><label>מספר רישיון / הסמכה</label><input id="twLic"><label>הגורם המנפיק</label><input id="twAuth"><label>שנות ניסיון</label><input id="twYears" type="number" min="0" max="80"><label>אזור פעילות</label><input id="twLoc"><label>שפות</label><input id="twLang" placeholder="עברית, אנגלית"><label>אודות מקצועי</label><textarea id="twBio"></textarea><button class="twbtn dark" data-tw-apply style="margin-top:10px">שליחת בקשה לאימות</button></div>'}
async function enhanceOwnProfile(force){if(!session)return;var role=q('#a4role');if(!role)return;if(role.value!=='therapist')role.value='member';role.style.display='none';var lab=role.previousElementSibling;if(lab&&lab.tagName==='LABEL')lab.style.display='none';var th=q('#a4ther');if(th&&role.value!=='therapist')th.classList.add('a4hidden');if(!q('#twOwnWall')){var b=document.createElement('button');b.id='twOwnWall';b.className='twbtn gold';b.textContent='הקיר שלי';b.style.marginBottom='10px';b.onclick=function(){publicProfile(session.user.id)};var m=q('#a4mount');if(m)m.insertBefore(b,m.firstChild)}if(!q('#twApplicationBox')||force){var old=q('#twApplicationBox');if(old)old.remove();var d=document.createElement('div');d.id='twApplicationBox';d.innerHTML=await applicationBox();var form=q('.a4form');if(form)form.insertAdjacentElement('afterend',d)}}
function injectProfileButtons(){document.querySelectorAll('[data-a4-chat]').forEach(function(b){var uid=b.getAttribute('data-a4-chat');var row=b.closest('.a4person');if(!uid||!row||row.querySelector('[data-tw-profile="'+uid+'"]'))return;var x=document.createElement('button');x.className='a4btn soft';x.setAttribute('data-tw-profile',uid);x.textContent='פרופיל';var acts=b.parentElement;acts.insertBefore(x,b)})}
async function review(id,ok){var note=ok?'':(prompt('סיבת דחייה (אופציונלי):')||'');var r=await sb.rpc('review_therapist_application',{p_application:id,p_approve:ok,p_note:note||null});if(r.error)return toast('הפעולה נכשלה: '+r.error.message);toast(ok?'המטפל אושר ✓':'הבקשה נדחתה');therapists()}
function bind(){document.addEventListener('click',function(ev){var t=ev.target.closest&&ev.target.closest('button');if(!t)return;if(t.id==='twNavBtn'){ev.preventDefault();ev.stopImmediatePropagation();therapists();return}if(t.dataset.twProfile){ev.preventDefault();ev.stopImmediatePropagation();publicProfile(t.dataset.twProfile);return}if(t.dataset.twChat){ev.preventDefault();ev.stopImmediatePropagation();directChat(t.dataset.twChat);return}if(t.dataset.twSend){sendMsg(t.dataset.twSend,t.dataset.twTo);return}if(t.hasAttribute('data-tw-publish')){publishWall();return}if(t.dataset.twDelete){deleteWall(t.dataset.twDelete);return}if(t.hasAttribute('data-tw-apply')){submitApplication();return}if(t.dataset.twApprove){review(t.dataset.twApprove,true);return}if(t.dataset.twReject){review(t.dataset.twReject,false);return}if(t.hasAttribute('data-tw-back')){therapists();return}},true);var tm=null;new MutationObserver(function(){clearTimeout(tm);tm=setTimeout(function(){nav();injectProfileButtons();enhanceOwnProfile(false)},120)}).observe(document.body,{childList:true,subtree:true})}
async function boot(){css();nav();sb=shared();if(!sb)return setTimeout(boot,100);var r=await sb.auth.getSession();session=r.data.session;if(session)await adminCheck();sb.auth.onAuthStateChange(async function(_e,s){session=s;if(session)await adminCheck()});bind();injectProfileButtons();enhanceOwnProfile(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();